### PR TITLE
Null Safety

### PR DESCRIPTION
**Pull request by benja8151**

### CODE REVIEW

**Comment by mikepyts** [comment]
Hello, thanks for efforts, have you planned some dates to realease it?

**Comment by wilpar** [comment]
Good work!  

While you're updating it you might as well update the showsnackbar to current as well:

ScaffoldMessenger.of(context).showSnackBar

**Comment by ChihchengHsieh** [comment]
Is it going to release soon?

**Comment by Manguelo** [comment]
Any news on this?

**Comment by vytautas-pranskunas-** [comment]
any news?

**Pull request closed without merging**
