### PR TITLE
Implement setStripeAccount

### PR DESCRIPTION
**Pull request by nicowernli**
This is a new PR implements setStripeAccount now based on https://github.com/tipsi/tipsi-stripe/pull/563/files

### CODE REVIEW

**Comment by jonasbark** [comment]
Can you fix the merge conflict? Then I'll merge this 👍

**Comment by nicowernli** [comment]
Hi @jonasbark I fixed the conflict already. I hope you have some time to merge the PR.

Bests

**Comment by macmatrix** [comment]
Hi @nicowernli

can you confirm what I should add to my pub spec file to try this one?

currently I have `stripe_payment: ^1.0.5`

Thanks !

**Comment by jonasbark** [comment]
Hi @nicowernli - there's some feedback on this PR: https://github.com/jonasbark/flutter_stripe_payment/issues/94#issuecomment-554574501

**Pull request merged**
