### PR TITLE
potential fix for issue #97

### PR DESCRIPTION
**Pull request by sandeep-at-airlift**

### CODE REVIEW

**Comment by jonasbark** [comment]
Yeah, it wouldn't compile like that.

**Comment by sandeep-at-airlift** [comment]
@jonasbark  guilty as charged... fixed the code closer to what @NickCullen had suggested. 
Lol.. I'm C#/Obj-C myself... I'm testing it right now.. i removed the cast as it doesn't add anything as the return type.

**Comment by NickCullen** [comment]
Looks good to me

**Comment by sandeep-at-airlift** [comment]
@jonasbark Any idea when this will make it to master in a release?

**Pull request merged**
