### PR TITLE
NullSafety

### PR DESCRIPTION
**Pull request by eliudio**

### CODE REVIEW

**Comment by vytautas-pranskunas-** [comment]
any news?

**Comment by eliudio** [comment]
@vytautas-pranskunas- I'll be as brief as you: no

**Comment by vytautas-pranskunas-** [comment]
@eliudio why no? This plugin is recommendet by stripe it self.. is it dead? what are elternative?
there is flutter_sdk library but it does not support appley and google pay.

**Comment by jonasbark** [comment]
@eliudio can you fix the merge conflict?

**Comment by vytautas-pranskunas-** [comment]
@jonasbark here you go:
https://github.com/jonasbark/flutter_stripe_payment/pull/289

**Pull request merged**
