### PR TITLE
Bug/193 example app   ios build failing 

### PR DESCRIPTION
**Pull request by dw2kim**
To resolve the below issue:

https://github.com/jonasbark/flutter_stripe_payment/issues/193

### CODE REVIEW

**Comment by akeblom** [comment]
Please merge this! Our build is failing due to this.

**Comment by jonasbark** [comment]
@akeblom are you talking about the example app that's failing to build or to you mean the "preserve card name" part?

**Comment by akeblom** [comment]
The failing build. Our CI/CD fails on this when archiving the app.

**Comment by dw2kim** [comment]
> Please merge this! Our build is failing due to this.

@akeblom 

> @akeblom are you talking about the example app that's failing to build or to you mean the "preserve card name" part?

Hi @jonasbark, can you approve these changes? 
It's pretty straightforward change.

**Comment by jonasbark** [comment]
The preserve card name part has already been merged a few days ago:
https://github.com/jonasbark/flutter_stripe_payment/commit/e5a64304e32fec9db8abbc70e2a183eac2986098

@akeblom can you please explain to me why you want to build the example app of this plugin on your CI system...?

**Comment by akeblom** [comment]
Of course I do not want to do that. 
But unless i bump the deployment target to 11.0 manually on the stripe-payment package "flutter build ios" wont succeed.

**Comment by jonasbark** [comment]
Okay I get that - but even when I merge this PR it won't have any effect on that. This PR only touches the Example app.
What you want is a change in https://github.com/jonasbark/flutter_stripe_payment/blob/master/ios/stripe_payment.podspec#L19

**Comment by akeblom** [comment]
Yes thats right. My bad!

**Comment by akeblom** [comment]
Until that change is in place I can try to downgrade the package a couple of versions.

**Comment by p02diada** [comment]
Same problem here

**Comment by MisterJimson** [comment]
I didn’t notice this PR, but I just opened #207 with a different fix for the sample app on iOS.

**Comment by Infinical** [comment]
@akeblom how did you fix this

> It might not be the example app that is causing the problem but rather the podspec file that sets the target to 10.
> 
> I get a lot of `PKPaymentRequestShippingMethodUpdate' is only available on iOS 11.0` and similar warnings and the the build fails.
> 
> If open Xcode and change build target to 11 on the stripe-payment pod the build is successful.

**Comment by akeblom** [comment]
I did cloned the project and used my local version instead of pub.dev. Then I changed the build target version in stripe_payment.podspec

**Pull request closed without merging**
