### PR TITLE
WIP: Update to 12.5 compatible stripe pod

### PR DESCRIPTION
**Pull request by mclark4386**
https://github.com/stripe/stripe-ios/releases/tag/v19.4.1 should hopefully solve #246

### CODE REVIEW

**Comment by jonasbark** [comment]
Thanks - can you adjust the changelog and version code as well?

**Comment by mclark4386** [comment]
Sorry about that, will do! I'm going to put this in WIP because they haven't release the actual cocoapod yet: https://github.com/stripe/stripe-ios/issues/1795 , hopefully that'll be a quick fix for them and then I'll mark this a ready (was mostly using this PR for testing, sorry I didn't mark it as WIP going into it!)

**Comment by mclark4386** [comment]
Updated! Will switch this off of WIP as soon as that pod is released!

**Comment by wilpar** [comment]
Ever notice how things break just when you need 'em?

**Comment by jonasbark** [comment]
Always wait before updating Xcode if you're using Flutter... :)

**Comment by chaesung** [comment]
Well according to stripe/stripe-ios#1767, it ain't coming.... would it be possible to move up to version 21.3.1 and change the min iOS version to 11?

**Comment by mclark4386** [comment]
about to make those changes to test...

**Comment by mclark4386** [comment]
Migration notes here: https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md make it sound like not such a big deal till you notice this link: https://stripe.com/docs/mobile/ios/sdk-21-migration?language=objc
so... yeah... may try to get that working with a find/replace, but this may not be as quick a fix as I hoped.

**Comment by mclark4386** [comment]
Well... The good news is it's building again. I'm not positive how to test it besides just building it into my app and trying it... didn't change anymore than I had to (including some deprecations that need to be fixed ASAP), so hopefully it'll be stable? I'll let y'all know if anything comes up.
Going to keep this as WIP at least until my build comes back bug free.

**Comment by chaesung** [comment]
Awesome. Hopefully everything works and gets merged.

**Comment by ag84ark** [comment]
I have applied your changes to my local copy of the plugin, it compiles, and I can run the project, but when i want to use the Stripe add card widget, the app gets killed. 
Maybe this is just by me, I have no experience with Swift.
This is what I get, maybe it can help:

`
2021-04-29 01:06:38.759459+0200 Runner[2065:1172147] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x20342f180 0x2026079f8 0x2033a8bec 0x203330898 0x203322934 0x203322710 0x22f625374 0x22f61e098 0x10d6c0b80 0x10d6c1018 0x10d5c3f38 0x10d5c2b98 0x10d561a00 0x10d5c4648 0x10d5c29f4 0x22f858224 0x22f858628 0x22f7d56bc 0x22f78b8f0 0x22f787d60 0x22fe0d0ac 0x22fdfbbfc 0x22fe28a6c 0x2033c04fc 0x2033bb224 0x2033bb7a0 0x2033bafb4 0x2055bc79c 0x22fe01c38 0x100645628 0x202e7e8e0) 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
terminating with uncaught exception of type NSException
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by mclark4386** [comment]
Going to close this because there is a better solution in #284 .

**Pull request closed without merging**
